# Generated by Django 4.2.7 on 2023-12-01 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_registereduser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registereduser',
        ),
    ]
