# Generated by Django 4.2.7 on 2023-12-01 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0004_registeredusers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registeredusers',
            old_name='firstname',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='registeredusers',
            old_name='lastname',
            new_name='password2',
        ),
        migrations.RemoveField(
            model_name='registeredusers',
            name='password',
        ),
        migrations.CreateModel(
            name='tutorialComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tutorial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
